---
- hosts: all
  become: yes
  tasks:
    - name: update packages
      ansible.builtin.apt:
        update_cache: yes

    - name: install ranger
      ansible.builtin.apt:
        name: ranger

    - name: install neofetch
      ansible.builtin.apt:
        name: neofetch
