---
- name: Install Prerequisites
  apt:
    name: "{{ item }}"
    update_cache: yes
    force_apt_get: yes
    state: latest
  loop: ["aptitude"]

- name: Allow ssh port & enable UFW
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp
    state: enabled
