---
# tasub teada: repo kloonimisel kasutatakse ansible masina ssh key'd, mitte target masina key'd
- name: Clone chat app private repository
  git:
    repo: "{{ GIT_REPO_URL }}"
    version: "{{ GIT_BRANCH }}"
    dest: "/home/{{ USER }}/{{ LOCAL_FOLDER_NAME }}"
    accept_hostkey: yes

- name: Build Docker image
  docker_image:
    build:
      path: "{{ DOCKERFILE_PATH }}"
    name: "{{ IMAGE_NAME }}"
    source: build
    force_source: true
    state: present

- name: Run Docker container
  docker_container:
    name: "{{ CONTAINER_NAME }}"
    image: "{{ IMAGE_NAME }}"
    # liidab konteineri vorgu hosti vorguga
    network_mode: host
    # recreate: true
    state: started
    restart_policy: unless-stopped

- name: Check that the nodejs server returns status 200
  ansible.builtin.uri:
    url: http://localhost:8080/status
    follow_redirects: none
    method: GET
  register: _result
  until: _result.status == 200
  retries: 5 # 5 * 3 seconds = max 15 seconds
  delay: 3 # Every 3 seconds

- name: Delete old Docker images
  docker_prune:
    images: true
