---
- name: Install Nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Delete default config
  file:
    state: absent
    path: /etc/nginx/sites-enabled/default

- name: Copy new Nginx config
  template:
    src: templates/app/nginx.conf.j2
    dest: /etc/nginx/sites-available/chatapp
  notify: Restart Nginx

- name: Enable new config
  file:
    src: /etc/nginx/sites-available/chatapp
    dest: /etc/nginx/sites-enabled/chatapp
    state: link
  notify: Restart Nginx

- name: Allow port 8080
  ufw:
    rule: allow
    port: "{{ NGINX_PORT }}"
    proto: tcp
