---
GIT_REPO_URL: git@github.com:lvastisson/loputoo-chat-app.git
GIT_BRANCH: master
USER: lauri
LOCAL_FOLDER_NAME: loputoo-chat-app-test
IMAGE_NAME: chatapp_backend
CONTAINER_NAME: chatapp_backend
DOCKERFILE_PATH: /home/{{ USER }}/{{ LOCAL_FOLDER_NAME }}/backend/
