---
- import_playbook: check-internet.yml
- import_playbook: apt-update.yml
- import_playbook: mongodb.yml
- import_playbook: docker.yml
- import_playbook: nginx.yml
- import_playbook: deploy-backend.yml