---
- name: Setup Zabbix server
  hosts: monitoring
  remote_user: root
  become: yes
  vars_files:
    - vars/main.yml

  tasks:
    - name: Create workspace folder
      ansible.builtin.file:
        path: "{{ workspace_folder }}"
        state: directory
        mode: "0755"

    - name: Install Prerequisites
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: latest
        force_apt_get: yes
      loop: ["aptitude", "python3-pymysql"]

    - name: Download Zabbix repository file
      ansible.builtin.get_url:
        url: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb"
        dest: "{{ workspace_folder }}/zabbix.deb"

    - name: Install Zabbix repository
      ansible.builtin.apt:
        deb: "{{ workspace_folder }}/zabbix.deb"

    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Zabbix server, frontend, agent
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: latest
      loop:
        [
          "zabbix-server-mysql",
          "zabbix-frontend-php",
          "zabbix-nginx-conf",
          "zabbix-sql-scripts",
          "zabbix-agent",
        ]

    - name: Create Zabbix database
      mysql_db:
        name: zabbix
        state: present
        encoding: "utf8mb4"
        collation: "utf8mb4_bin"
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create Zabbix database user
      community.mysql.mysql_user:
        name: zabbix
        password: "{{ mysql_zabbix_password }}"
        priv: "zabbix.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Copy Zabbix db dump file
      copy:
        src: "{{ playbook_dir }}/templates/monitoring/zabbix/zabbixdb_dump.sql"
        dest: /tmp/dump.sql

    # might need to add "set global log_bin_trust_function_creators = 1;" in case of errors
    - name: Import Zabbix db
      mysql_db:
        name: zabbix
        state: import
        target: /tmp/dump.sql
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Copy Zabbix config files
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      loop:
        - src: "{{ playbook_dir }}/templates/monitoring/zabbix/nginx.conf.j2"
          dest: "/etc/zabbix/nginx.conf"
        - src: "{{ playbook_dir }}/templates/monitoring/zabbix/php-fpm.conf.j2"
          dest: "/etc/zabbix/php-fpm.conf"
        - src: "{{ playbook_dir }}/templates/monitoring/zabbix/zabbix_agentd.conf.j2"
          dest: "/etc/zabbix/zabbix_agentd.conf"
        - src: "{{ playbook_dir }}/templates/monitoring/zabbix/zabbix_server.conf.j2"
          dest: "/etc/zabbix/zabbix_server.conf"
        - src: "{{ playbook_dir }}/templates/monitoring/zabbix/web/zabbix.conf.php.j2"
          dest: "/etc/zabbix/web/zabbix.conf.php"

    - name: Restart and enable Zabbix server and agent processes
      service:
        name: "{{ item }}"
        state: restarted
        enabled: true
      become: true
      loop:
        - zabbix-server
        - zabbix-agent
        - nginx
        - php8.1-fpm

    - name: "UFW - Allow HTTP on port {{ zabbix_port }}"
      ufw:
        rule: allow
        port: "{{ zabbix_port }}"
        proto: tcp
# TODO: Check Zabbix frontend is accessible
